/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorium;

import form.Form_Dokter;
import form.Form_Layanan;
import form.Form_pasien;
import form.form_hasil;
import form.form_pembayaran;
import form.form_pendaftaran;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        showDateTime();
        execute();
        ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo_lab.png"));
        ImageIcon Nama_lab = new ImageIcon(getClass().getResource("/img/nama_lab.png"));
        ImageIcon Logo_pn = new ImageIcon(getClass().getResource("/img/pn_utama.jpg"));
        
        Logo.setIcon(logo);
        nama_lab.setIcon(Nama_lab);
        logo_pn.setIcon(Logo_pn);
    }
     private void showDateTime() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat hari = new SimpleDateFormat("EEEE");
                SimpleDateFormat tanggal = new SimpleDateFormat("dd MMMM yyyy ");
                SimpleDateFormat waktu = new SimpleDateFormat("HH:mm:ss");
                lblHari.setText(hari.format(now));
                lblTanggal.setText(tanggal.format(now));
                lblWaktu.setText(waktu.format(now));
            }
        });
        timer.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_header = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        nama_lab = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblWaktu = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblHari = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_isi = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        logo_pn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_header.setBackground(new java.awt.Color(255, 255, 255));
        pn_header.setPreferredSize(new java.awt.Dimension(821, 70));

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout pn_headerLayout = new javax.swing.GroupLayout(pn_header);
        pn_header.setLayout(pn_headerLayout);
        pn_headerLayout.setHorizontalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pn_headerLayout.setVerticalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(nama_lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_header, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 512));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblWaktu.setBackground(new java.awt.Color(255, 255, 255));
        lblWaktu.setText("jLabel2");

        lblTanggal.setBackground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("jLabel2");

        lblHari.setBackground(new java.awt.Color(255, 255, 255));
        lblHari.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblHari, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_isi.setBackground(new java.awt.Color(204, 204, 204));

        pn_utama.setBackground(new java.awt.Color(204, 204, 204));
        pn_utama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pn_utama.setName(""); // NOI18N
        pn_utama.setLayout(new java.awt.BorderLayout());

        logo_pn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pn_utama.add(logo_pn, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pn_isiLayout = new javax.swing.GroupLayout(pn_isi);
        pn_isi.setLayout(pn_isiLayout);
        pn_isiLayout.setHorizontalGroup(
            pn_isiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        pn_isiLayout.setVerticalGroup(
            pn_isiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        getContentPane().add(pn_isi, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(774, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pn_utama.add(new pn_utama());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JLabel logo_pn;
    private javax.swing.JLabel nama_lab;
    private javax.swing.JPanel pn_header;
    private javax.swing.JPanel pn_isi;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/img/Master.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/img/transaction.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/img/laporan.png"));
        ImageIcon iconDokter = new ImageIcon(getClass().getResource("/img/ms_doctor.png"));
        ImageIcon iconPasien = new ImageIcon(getClass().getResource("/img/ms_pasien.png"));
        ImageIcon iconLayanan = new ImageIcon(getClass().getResource("/img/ms_layanan.png"));
        ImageIcon iconPendaftaran = new ImageIcon(getClass().getResource("/img/tr_Pedaftaran.png"));
        ImageIcon iconHasil = new ImageIcon(getClass().getResource("/img/tr_hasil.png"));
        ImageIcon iconPembayaran = new ImageIcon(getClass().getResource("/img/tr_pembayaran.png"));
        ImageIcon iconLpPriksa = new ImageIcon(getClass().getResource("/img/lp_Pemeriksaan.png"));
        ImageIcon iconLpKinerja = new ImageIcon(getClass().getResource("/img/lp_Hasil.png"));
        ImageIcon iconLpKeuangan = new ImageIcon(getClass().getResource("/img/lp_keuangan.png"));
        ImageIcon iconLphasil = new ImageIcon(getClass().getResource("/img/lp_Hasil.png"));
        ImageIcon Logo_pn = new ImageIcon(getClass().getResource("/img/pn_utama.jpg"));
        
        Item_menu masDokter = new Item_menu(null, true, iconDokter, "Dokter", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Dokter());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        Item_menu masPasien = new Item_menu(null, true, iconPasien, "Pasien", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_pasien());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
            });
        Item_menu masLayanan = new Item_menu(null, true, iconLayanan, "Layanan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Form_Layanan());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
            });
        
        Item_menu pendaftaran = new Item_menu(null, true, iconPendaftaran, "Pendaftaran", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new form_pendaftaran());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
            });
        Item_menu inputhasil = new Item_menu(null, true, iconHasil, "Input Hasil",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new form_hasil());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
            });
        Item_menu pembayaran = new Item_menu(null, true, iconPembayaran, "Pembayaran", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new form_pembayaran());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
            });
        
        Item_menu lpHasil = new Item_menu(null, true, iconLphasil, "Hasil", null);
        Item_menu lpPemeriksaan = new Item_menu(null, true, iconLpPriksa, "Pemeriksaan", null);
        Item_menu lpkinerja = new Item_menu(null, true, iconLpKinerja, "Kinerja", null);
        Item_menu lpKeuangan = new Item_menu(null, true, iconLpKeuangan, "Pemeriksaan", null);
        
        Item_menu menuHome = new Item_menu(iconMaster, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new pn_utama());
                pn_utama.repaint();
                pn_utama.revalidate();
                logo_pn.setIcon(Logo_pn);
            }
        });
        Item_menu menuLogout = new Item_menu(iconMaster, false, null, "Logout", new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin logout?", "Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Buka form login
                    Login fa = new Login();
                    fa.show();
                    removeAll();
                    repaint();
                    revalidate();
            }
        }
    });
        Item_menu menuMaster = new Item_menu(null, false, iconMaster, "master", null, masDokter, masPasien, masLayanan);
        Item_menu menuTransaksi = new Item_menu(null, false, iconTransaksi, "Transaksi", null, pendaftaran, inputhasil, pembayaran);
        Item_menu menuReport = new Item_menu(null, false, iconReport, "Report", null, lpHasil, lpPemeriksaan, lpkinerja, lpKeuangan);
        
        addMenu(menuHome, menuMaster,menuTransaksi,menuReport,menuLogout);
    }
    
    private void addMenu(Item_menu... menu){
        for(int i = 0; i < menu.length; i++){
            pn_menu.add(menu[i]);
            ArrayList<Item_menu> subMenu = menu[i].getSubMenu();
            for(Item_menu m : subMenu){
                addMenu(m);
            }
            pn_menu.revalidate();
        }
    }
}
