/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Dokter extends javax.swing.JPanel {

    /**
     * Creates new form Form_Dokter
     */
    public Form_Dokter() {
        initComponents();
        tampilkanData();
        
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
    }
    
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Dokter");
    model.addColumn("Nama");
    model.addColumn("Kontak");
    model.addColumn("Spesialis");
    model.addColumn("Alamat");

    try {
        String sql = "SELECT * FROM dokter";
        Connection kon = koneksi.koneksiDb();
        Statement stm = kon.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("Id_Dokter"),
                res.getString("Nama"),
                res.getString("Kontak"),
                res.getString("spesialis"),
                res.getString("Alamat"),
            });
        }

        tabel_dokter.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataDokter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_dokter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_batal = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        caridata = new javax.swing.JTextField();
        bt_cardat = new javax.swing.JButton();
        TambahDokter = new javax.swing.JPanel();
        bt_batalTambah = new javax.swing.JButton();
        bt_Simpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Id_Dokter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nama_dokter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Kontak = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Spesialis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataDokter.setBackground(new java.awt.Color(255, 255, 255));

        tabel_dokter.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tabel_dokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_dokter);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("DATA DOKTER");

        bt_batal.setBackground(new java.awt.Color(213, 213, 0));
        bt_batal.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_batal.setText("BATAL");
        bt_batal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_batal.setBorderPainted(false);
        bt_batal.setPreferredSize(new java.awt.Dimension(47, 27));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_tambah.setBackground(new java.awt.Color(0, 173, 68));
        bt_tambah.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_tambah.setText("TAMBAH");
        bt_tambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_tambah.setBorderPainted(false);
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(222, 0, 0));
        bt_hapus.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_hapus.setText("HAPUS");
        bt_hapus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_hapus.setBorderPainted(false);
        bt_hapus.setPreferredSize(new java.awt.Dimension(59, 27));
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("Cari Data");

        bt_cardat.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bt_cardat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search (1) (1).png"))); // NOI18N
        bt_cardat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cardat.setPreferredSize(new java.awt.Dimension(50, 50));
        bt_cardat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cardatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataDokterLayout = new javax.swing.GroupLayout(dataDokter);
        dataDokter.setLayout(dataDokterLayout);
        dataDokterLayout.setHorizontalGroup(
            dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
            .addGroup(dataDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataDokterLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dataDokterLayout.createSequentialGroup()
                        .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataDokterLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caridata))
                            .addGroup(dataDokterLayout.createSequentialGroup()
                                .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataDokterLayout.setVerticalGroup(
            dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataDokter, "card2");

        TambahDokter.setBackground(new java.awt.Color(255, 255, 255));

        bt_batalTambah.setBackground(new java.awt.Color(255, 255, 102));
        bt_batalTambah.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_batalTambah.setText("BATAL");
        bt_batalTambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_batalTambah.setBorderPainted(false);
        bt_batalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalTambahActionPerformed(evt);
            }
        });

        bt_Simpan.setBackground(new java.awt.Color(51, 255, 0));
        bt_Simpan.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bt_Simpan.setText("SIMPAN");
        bt_Simpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_Simpan.setBorderPainted(false);
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel7.setText("DATA DOKTER");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("ID DOKTER");

        Id_Dokter.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Id_Dokter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Id_Dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_DokterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Nama Dokter");

        Nama_dokter.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Nama_dokter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Kontak");

        Kontak.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Kontak.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Kontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KontakActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("Spesialis");

        Spesialis.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Spesialis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Spesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpesialisActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setText("Alamat");

        Alamat.setColumns(20);
        Alamat.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Alamat.setRows(5);
        Alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(Alamat);

        javax.swing.GroupLayout TambahDokterLayout = new javax.swing.GroupLayout(TambahDokter);
        TambahDokter.setLayout(TambahDokterLayout);
        TambahDokterLayout.setHorizontalGroup(
            TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id_Dokter, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nama_dokter)
                    .addComponent(Kontak)
                    .addComponent(Spesialis)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TambahDokterLayout.createSequentialGroup()
                        .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(TambahDokterLayout.createSequentialGroup()
                                .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 509, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TambahDokterLayout.setVerticalGroup(
            TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        mainPanel.add(TambahDokter, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // batal utama
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        bt_tambah.setText("Tambah");
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:                                       
    int selectedRow = tabel_dokter.getSelectedRow();
    
    if (selectedRow != -1) {
        int idDokter = Integer.parseInt(tabel_dokter.getValueAt(selectedRow, 0).toString());

        int konfirmasi = JOptionPane.showConfirmDialog(null, 
            "Yakin ingin menghapus data ini?", "Konfirmasi", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection kon = koneksi.koneksiDb();
                String sql = "DELETE FROM dokter WHERE id_Dokter = ?";
                PreparedStatement pst = kon.prepareStatement(sql);
                pst.setInt(1, idDokter);
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabel_dokter.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
    }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_batalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalTambahActionPerformed
        //  batal tambah data
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(dataDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        Id_Dokter.setText("");
        Nama_dokter.setText("");
        Kontak.setText("");
       
    }//GEN-LAST:event_bt_batalTambahActionPerformed

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO dokter(id_dokter, nama, kontak, spesialis, alamat)VALUES (?, ?, ?, ?, ?)" +
                "ON DUPLICATE KEY UPDATE nama = VALUES(nama), kontak = VALUES(kontak),"+
                "spesialis = VALUES(spesialis), alamat = VALUES(alamat) ";
        Connection kon = koneksi.koneksiDb();
        PreparedStatement pst = kon.prepareStatement(sql);
        pst.setString(1, Id_Dokter.getText());
        pst.setString(2, Nama_dokter.getText());
        pst.setString(3, Kontak.getText());
        pst.setString(4, Spesialis.getText());
        pst.setString(5, Alamat.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan! / ");
        Id_Dokter.setText("");
        Nama_dokter.setText("");
        Kontak.setText("");
        Spesialis.setText("");
        Alamat.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
    }
    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
       int selectedRow = tabel_dokter.getSelectedRow();
           
        if (selectedRow != -1) {
        // Ambil data dari tabel
        String id = tabel_dokter.getValueAt(selectedRow, 0).toString();
        String nama = tabel_dokter.getValueAt(selectedRow, 1).toString();
        String kontak = tabel_dokter.getValueAt(selectedRow, 2).toString();
        String spesialis = tabel_dokter.getValueAt(selectedRow, 3).toString();
        String alamat = tabel_dokter.getValueAt(selectedRow, 4).toString();

        // Masukkan ke text field di panel Formulir
        Id_Dokter.setText(id);
        Nama_dokter.setText(nama);
        Kontak.setText(kontak);
        Spesialis.setText(spesialis);
        Alamat.setText(alamat);

        // Tampilkan panel formulir
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(TambahDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
    } else {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(TambahDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    } 
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void KontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KontakActionPerformed

    private void tabel_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dokterMouseClicked
        // TODO add your handling code here:
        bt_hapus.setVisible(true);
        bt_batal.setVisible(true);

        
        bt_tambah.setText("EDIT");
    }//GEN-LAST:event_tabel_dokterMouseClicked

    private void Id_DokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_DokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_DokterActionPerformed

    private void bt_cardatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cardatActionPerformed
        // TODO add your handling code here:
        String Sql = "SELECT * FROM dokter WHERE Nama like '%"+caridata.getText()+"%'";
        Connection kon = koneksi.koneksiDb();

        try{
            java.sql.Statement stat = kon.createStatement();
            ResultSet hasil = stat.executeQuery(Sql);

            DefaultTableModel model = (DefaultTableModel) tabel_dokter.getModel();
            model.setRowCount(0);
            while(hasil.next()){
                String a = hasil.getString("id_dokter");
                String b = hasil.getString("Nama");
                String c = hasil.getString("Kontak");
                String d = hasil.getString("spesialis");
                String e = hasil.getString("Alamat");

                String[] data = {a, b, c, d, e};
                model.addRow(data);

            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_bt_cardatActionPerformed

    private void SpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpesialisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Id_Dokter;
    private javax.swing.JTextField Kontak;
    private javax.swing.JTextField Nama_dokter;
    private javax.swing.JTextField Spesialis;
    private javax.swing.JPanel TambahDokter;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalTambah;
    private javax.swing.JButton bt_cardat;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JTextField caridata;
    private javax.swing.JPanel dataDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tabel_dokter;
    // End of variables declaration//GEN-END:variables
}
