/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class Form_pasien extends javax.swing.JPanel {

    /**
     * Creates new form Form_pasien
     */
    public Form_pasien() {
        initComponents();
        loadGolonganDarah();
        loadJenisKelamin();
        tampilkanData();
        generateIdPasien();
        
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        
        JDateChooser TanggalLahir = new JDateChooser();
        TanggalLahir.setDateFormatString("yyyy-MM-dd"); // format sesuai DB
        tambahPasien.add(TanggalLahir); // masukkan ke panel

    } 
    
    private void loadGolonganDarah() {
        try {
            String sql = "SHOW COLUMNS FROM pasien LIKE 'goldar'";
            Connection kon = koneksi.koneksiDb();
            PreparedStatement pst = kon.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String enumStr = rs.getString("Type"); // enum('A','B','AB','O')
                enumStr = enumStr.replace("enum(", "").replace(")", "").replace("'", "");
                String[] values = enumStr.split(",");

                Goldar.removeAllItems();
                for (String value : values) {
                    Goldar.addItem(value);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load ENUM: " + e.getMessage());
        }
    }
    
    private void loadJenisKelamin() {
        try {
            String sql = "SHOW COLUMNS FROM pasien LIKE 'jk'";
            Connection kon = koneksi.koneksiDb();
            PreparedStatement pst = kon.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String enumStr = rs.getString("Type"); 
                enumStr = enumStr.replace("enum(", "").replace(")", "").replace("'", "");
                String[] values = enumStr.split(",");

                JK.removeAllItems();
                for (String value : values) {
                    JK.addItem(value);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load ENUM: " + e.getMessage());
        }
    }

    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pasien");
    model.addColumn("Nama");
    model.addColumn("Alamat");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Telepon");
    model.addColumn("Tanggal Lahir");
    model.addColumn("Tinggi Badan");
    model.addColumn("Berat Badan");
    model.addColumn("Gol. Darah");

    try {
        String sql = "SELECT * FROM pasien";
        Connection kon = koneksi.koneksiDb();
        Statement stm = kon.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("No_rm"),
                res.getString("Nama"),
                res.getString("Alamat"),
                res.getString("jk"),
                res.getString("no_telp"),
                res.getString("Tgl_lahir"),
                res.getDouble("Tinggi"),
                res.getDouble("Berat"),
                res.getString("goldar")
            });
        }

        tabel_pasien.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
    
    
}
    
    public void generateIdPasien() {
    try {
        Connection kon = koneksi.koneksiDb();
        String sql = "SELECT MAX(RIGHT(No_rm, 3)) FROM pasien";
        PreparedStatement pst = kon.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int id = rs.getString(1) != null ? Integer.parseInt(rs.getString(1)) + 1 : 1;
            String kode = String.format("%03d", id); // hasil: PS001, PS002
            IdPasien.setText(kode);
        } else {
            IdPasien.setText("001");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal generate ID: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataPasien = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_pasien = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        bt_batal = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        caridata = new javax.swing.JTextField();
        bt_cardat = new javax.swing.JButton();
        tambahPasien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_Simpan = new javax.swing.JButton();
        bt_batalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IdPasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NamaPasien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Telepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TinggiBadan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BeratBadan = new javax.swing.JTextField();
        Goldar = new javax.swing.JComboBox<>();
        JK = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        TanggalLahir = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataPasien.setBackground(new java.awt.Color(255, 255, 255));

        tabel_pasien.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tabel_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pasienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_pasien);

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel12.setText("DATA PASIEN");

        bt_batal.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_batal.setText("Batal");
        bt_batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_batal.setOpaque(false);
        bt_batal.setPreferredSize(new java.awt.Dimension(91, 23));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_tambah.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_tambah.setText("Tambah Data");
        bt_tambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_tambah.setOpaque(false);
        bt_tambah.setPreferredSize(new java.awt.Dimension(91, 23));
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_hapus.setOpaque(false);
        bt_hapus.setPreferredSize(new java.awt.Dimension(91, 23));
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("Cari Data");

        bt_cardat.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_cardat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search (1) (1).png"))); // NOI18N
        bt_cardat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cardat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cardatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPasienLayout = new javax.swing.GroupLayout(dataPasien);
        dataPasien.setLayout(dataPasienLayout);
        dataPasienLayout.setHorizontalGroup(
            dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
            .addGroup(dataPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPasienLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caridata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataPasienLayout.createSequentialGroup()
                        .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(dataPasienLayout.createSequentialGroup()
                                .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataPasienLayout.setVerticalGroup(
            dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(20, 20, 20)
                .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bt_batal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        mainPanel.add(dataPasien, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("TambahPasien");

        bt_Simpan.setBackground(new java.awt.Color(0, 235, 21));
        bt_Simpan.setText("SIMPAN");
        bt_Simpan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        bt_batalTambah.setText("Batal");
        bt_batalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalTambahActionPerformed(evt);
            }
        });

        jLabel3.setText("ID PASIEN");

        IdPasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setText("NAMA PASIEN");

        NamaPasien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setText("ALAMAT");

        Telepon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane2.setViewportView(Alamat);

        jLabel6.setText("NO TELEPON");

        jLabel7.setText("TINGGI BADAN");

        jLabel8.setText("GOLONGAN DARAH");

        jLabel9.setText("TANGGAL LAHIR");

        TinggiBadan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel10.setText("BERAT BADAN");

        BeratBadan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel11.setText("JENIS KELAMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdPasien)
                            .addComponent(Telepon)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TinggiBadan, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(TanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BeratBadan, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(JK, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinggiBadan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeratBadan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahPasienLayout = new javax.swing.GroupLayout(tambahPasien);
        tambahPasien.setLayout(tambahPasienLayout);
        tambahPasienLayout.setHorizontalGroup(
            tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPasienLayout.createSequentialGroup()
                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPasienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahPasienLayout.createSequentialGroup()
                        .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahPasienLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(tambahPasienLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 542, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahPasienLayout.setVerticalGroup(
            tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        mainPanel.add(tambahPasien, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tglLahir = sdf.format(TanggalLahir.getDate());
    try {
        String sql = "INSERT INTO pasien(No_rm, Nama, Alamat, jk, no_telp, Tgl_Lahir, Tinggi, Berat, goldar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"+
                "ON DUPLICATE KEY UPDATE " +
                 "nama = VALUES(Nama), alamat = VALUES(Alamat), jk = VALUES(jk), " +
                 "no_telp = VALUES(no_telp), tgl_lahir = VALUES(Tgl_Lahir), " +
                 "tinggi = VALUES(Tinggi), berat = VALUES(Berat), goldar = VALUES(goldar)";
        Connection kon = koneksi.koneksiDb();
        PreparedStatement pst = kon.prepareStatement(sql);
        pst.setString(1, IdPasien.getText());  // Tambahkan ID Pasien
        pst.setString(2, NamaPasien.getText());
        pst.setString(3, Alamat.getText());
        pst.setString(4, JK.getSelectedItem().toString());
        pst.setString(5, Telepon.getText());
        pst.setString(6, tglLahir); // Format: YYYY-MM-DD
        pst.setDouble(7, Double.parseDouble(TinggiBadan.getText()));
        pst.setDouble(8, Double.parseDouble(BeratBadan.getText()));
        pst.setString(9, Goldar.getSelectedItem().toString());

        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        IdPasien.setText("");
        NamaPasien.setText("");
        Alamat.setText("");
        Telepon.setText("");
        TanggalLahir.setDate(null);
        TinggiBadan.setText("");
        BeratBadan.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
    }

    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_batalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalTambahActionPerformed
        // TODO add your handling code here:
        IdPasien.setText("");
        NamaPasien.setText("");
        Alamat.setText("");
        Telepon.setText("");
        TanggalLahir.setDate(null);
        TinggiBadan.setText("");
        BeratBadan.setText("");
        
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(dataPasien);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_batalTambahActionPerformed

    private void tabel_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pasienMouseClicked
        // TODO add your handling code here:
        bt_hapus.setVisible(true);
        bt_batal.setVisible(true);
        bt_tambah.setText("EDIT");;
    }//GEN-LAST:event_tabel_pasienMouseClicked

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // batal utama
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        bt_tambah.setText("Tambah");;
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_pasien.getSelectedRow();
           
        if (selectedRow != -1) {
        // Ambil data dari tabel
        String id = tabel_pasien.getValueAt(selectedRow, 0).toString();
        String nama = tabel_pasien.getValueAt(selectedRow, 1).toString();
        String alamat = tabel_pasien.getValueAt(selectedRow, 2).toString();
        String jk = tabel_pasien.getValueAt(selectedRow, 3).toString();
        String telepon = tabel_pasien.getValueAt(selectedRow, 4).toString();
        String tgl_lahir = tabel_pasien.getValueAt(selectedRow, 5).toString();
        String tinggi = tabel_pasien.getValueAt(selectedRow, 6).toString();
        String berat = tabel_pasien.getValueAt(selectedRow, 7).toString();
        String goldar = tabel_pasien.getValueAt(selectedRow, 8).toString();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        // Masukkan ke text field di panel Formulir
        IdPasien.setText(id );
        NamaPasien.setText(nama);
        Alamat.setText(alamat);
        Telepon.setText(telepon);
        try {
        Date tglLahir = sdf.parse(tgl_lahir); // ubah dari String ke Date
        TanggalLahir.setDate(tglLahir);         // isi ke JDateChooser
        } catch (ParseException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Format tanggal tidak valid!");
        }
        TinggiBadan.setText(tinggi);
        BeratBadan.setText(berat);
        JK.setSelectedItem(jk);
        Goldar.setSelectedItem(goldar);

        // Tampilkan panel formulir
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahPasien);
        mainPanel.repaint();
        mainPanel.revalidate();
    } else {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahPasien);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    } 
        
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_pasien.getSelectedRow();
    
    if (selectedRow != -1) {
        int idDokter = Integer.parseInt(tabel_pasien.getValueAt(selectedRow, 0).toString());

        int konfirmasi = JOptionPane.showConfirmDialog(null, 
            "Yakin ingin menghapus data ini?", "Konfirmasi", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection kon = koneksi.koneksiDb();
                String sql = "DELETE FROM pasien WHERE No_rm = ?";
                PreparedStatement pst = kon.prepareStatement(sql);
                pst.setInt(1, idDokter);
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabel_pasien.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
    }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_cardatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cardatActionPerformed
        // TODO add your handling code here:
        String Sql = "SELECT * FROM pasien WHERE Nama like '%"+caridata.getText()+"%'";
        Connection kon = koneksi.koneksiDb();
            
        try{            
            java.sql.Statement stat = kon.createStatement();
            ResultSet hasil = stat.executeQuery(Sql);
            
            DefaultTableModel model = (DefaultTableModel) tabel_pasien.getModel();
            model.setRowCount(0);
            while(hasil.next()){
                String a = hasil.getString("No_rm");
                String b = hasil.getString("Nama");
                String c = hasil.getString("Alamat");
                String d = hasil.getString("jk");
                String e = hasil.getString("no_telp");
                String f = hasil.getString("Tgl_Lahir");
                String g = String.valueOf(hasil.getDouble("Tinggi"));
                String h = String.valueOf(hasil.getDouble("Berat"));
                String i = hasil.getString("goldar"); // kalau ada kolom goldar

                String[] data = {a, b, c, d, e, f, g, h, i};
                model.addRow(data);
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_bt_cardatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField BeratBadan;
    private javax.swing.JComboBox<String> Goldar;
    private javax.swing.JTextField IdPasien;
    private javax.swing.JComboBox<String> JK;
    private javax.swing.JTextField NamaPasien;
    private com.toedter.calendar.JDateChooser TanggalLahir;
    private javax.swing.JTextField Telepon;
    private javax.swing.JTextField TinggiBadan;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalTambah;
    private javax.swing.JButton bt_cardat;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JTextField caridata;
    private javax.swing.JPanel dataPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tabel_pasien;
    private javax.swing.JPanel tambahPasien;
    // End of variables declaration//GEN-END:variables
}
