/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Layanan extends javax.swing.JPanel {

    /**
     * Creates new form Form__Layanan
     */
    public Form_Layanan() {
        initComponents();
        tampilkanData();
        
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        
    }
private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Layanan");
    model.addColumn("Nama Layanan");
    model.addColumn("Harga");

    try {
        String sql = "SELECT * FROM layanan";
        Connection kon = koneksi.koneksiDb();
        Statement stm = kon.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_layanan"),
                res.getString("nama_layanan"),
                res.getString("harga"),
            });
        }

        tabel_Layanan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        DataLayanan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_Layanan = new javax.swing.JTable();
        bt_batal = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        caridata = new javax.swing.JTextField();
        bt_cardat = new javax.swing.JButton();
        TambahLayanan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_Simpan = new javax.swing.JButton();
        bt_batalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id_layanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_layanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        harga_layanan = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        DataLayanan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("DATA LAYANAN");

        tabel_Layanan.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tabel_Layanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_Layanan.setGridColor(new java.awt.Color(0, 0, 0));
        tabel_Layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_LayananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_Layanan);

        bt_batal.setBackground(new java.awt.Color(255, 255, 0));
        bt_batal.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_batal.setText("Batal");
        bt_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_batal.setBorderPainted(false);
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_tambah.setBackground(new java.awt.Color(38, 220, 240));
        bt_tambah.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_tambah.setText("Tambah Data");
        bt_tambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_tambah.setBorderPainted(false);
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(240, 16, 14));
        bt_hapus.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_hapus.setBorderPainted(false);
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("Cari Data");

        bt_cardat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search (1) (1).png"))); // NOI18N
        bt_cardat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cardat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cardatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataLayananLayout = new javax.swing.GroupLayout(DataLayanan);
        DataLayanan.setLayout(DataLayananLayout);
        DataLayananLayout.setHorizontalGroup(
            DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(DataLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataLayananLayout.createSequentialGroup()
                        .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(DataLayananLayout.createSequentialGroup()
                                .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 436, Short.MAX_VALUE))
                    .addGroup(DataLayananLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caridata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cardat)))
                .addContainerGap())
        );
        DataLayananLayout.setVerticalGroup(
            DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );

        mainPanel.add(DataLayanan, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tambah Layanan");

        bt_Simpan.setBackground(new java.awt.Color(0, 235, 21));
        bt_Simpan.setText("SIMPAN");
        bt_Simpan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        bt_batalTambah.setText("Batal");
        bt_batalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalTambahActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Layanan");

        id_layanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Nama Layanan");

        nama_layanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Harga Layanan");

        harga_layanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_layanan)
                    .addComponent(nama_layanan)
                    .addComponent(harga_layanan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 682, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harga_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TambahLayananLayout = new javax.swing.GroupLayout(TambahLayanan);
        TambahLayanan.setLayout(TambahLayananLayout);
        TambahLayananLayout.setHorizontalGroup(
            TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TambahLayananLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 640, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(TambahLayananLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TambahLayananLayout.setVerticalGroup(
            TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(TambahLayanan, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        // TODO add your handling code here:
        try {
    String sql = "INSERT INTO layanan (id_layanan, nama_layanan, harga) VALUES (?, ?, ?) " +
             "ON DUPLICATE KEY UPDATE nama_layanan = VALUES(nama_layanan), harga = VALUES(harga)";

    Connection kon = koneksi.koneksiDb(); // pastikan method ini benar mengembalikan koneksi
    PreparedStatement pst = kon.prepareStatement(sql);

    pst.setString(1, id_layanan.getText());
    pst.setString(2, nama_layanan.getText());
    pst.setDouble(3, Double.parseDouble(harga_layanan.getText())); // parsing harga ke double

    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Layanan berhasil disimpan!");

    // Kosongkan field setelah simpan
    id_layanan.setText("");
    nama_layanan.setText("");
    harga_layanan.setText("");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal menyimpan layanan: " + e.getMessage());
}
    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_batalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalTambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(DataLayanan);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        id_layanan.setText("");
        nama_layanan.setText("");
        harga_layanan.setText("");
    }//GEN-LAST:event_bt_batalTambahActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // batal utama
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);

        bt_tambah.setText("Tambah");
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_Layanan.getSelectedRow();
           
        if (selectedRow != -1) {
        // Ambil data dari tabel
        String id = tabel_Layanan.getValueAt(selectedRow, 0).toString();
        String nama = tabel_Layanan.getValueAt(selectedRow, 1).toString();
        String harga = tabel_Layanan.getValueAt(selectedRow, 2).toString();
        

        // Masukkan ke text field di panel Formulir
        id_layanan.setText(id );
        nama_layanan.setText(nama);
        harga_layanan.setText(harga);

        // Tampilkan panel formulir
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(TambahLayanan);
        mainPanel.repaint();
        mainPanel.revalidate();
    } else {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(TambahLayanan);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    } 


    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_Layanan.getSelectedRow();

        if (selectedRow != -1) {
            int id_layanan = Integer.parseInt(tabel_Layanan.getValueAt(selectedRow, 0).toString());

            int konfirmasi = JOptionPane.showConfirmDialog(null,
                "Yakin ingin menghapus data ini?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    Connection kon = koneksi.koneksiDb();
                    String sql = "DELETE FROM layanan WHERE id_layanan = ?";
                    PreparedStatement pst = kon.prepareStatement(sql);
                    pst.setInt(1, id_layanan);
                    pst.executeUpdate();

                    DefaultTableModel model = (DefaultTableModel) tabel_Layanan.getModel();
                    model.removeRow(selectedRow);

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void tabel_LayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_LayananMouseClicked
        // TODO add your handling code here:
        bt_hapus.setVisible(true);
        bt_batal.setVisible(true);
        
        bt_tambah.setText("Edit");
    }//GEN-LAST:event_tabel_LayananMouseClicked

    private void bt_cardatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cardatActionPerformed
        // TODO add your handling code here:
        String Sql = "SELECT * FROM layanan WHERE nama_layanan like '%"+caridata.getText()+"%'";
        Connection kon = koneksi.koneksiDb();

        try{
            java.sql.Statement stat = kon.createStatement();
            ResultSet hasil = stat.executeQuery(Sql);

            DefaultTableModel model = (DefaultTableModel) tabel_Layanan.getModel();
            model.setRowCount(0);
            while(hasil.next()){
                String a = hasil.getString("id_layanan");
                String b = hasil.getString("nama_layanan");
                String c = hasil.getString("harga");

                String[] data = {a, b, c};
                model.addRow(data);

            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_bt_cardatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataLayanan;
    private javax.swing.JPanel TambahLayanan;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalTambah;
    private javax.swing.JButton bt_cardat;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JTextField caridata;
    private javax.swing.JTextField harga_layanan;
    private javax.swing.JTextField id_layanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nama_layanan;
    private javax.swing.JTable tabel_Layanan;
    // End of variables declaration//GEN-END:variables
}
