/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Dokter extends javax.swing.JPanel {

    /**
     * Creates new form Form_Dokter
     */
    public Form_Dokter() {
        initComponents();
        tampilkanData();
        
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        bt_edit.setVisible(false);
    }
    
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Dokter");
    model.addColumn("Nama");
    model.addColumn("Kontak");

    try {
        String sql = "SELECT * FROM dokter";
        Connection kon = koneksi.koneksiDb();
        Statement stm = kon.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("Id_Dokter"),
                res.getString("Nama"),
                res.getString("Kontak"),
            });
        }

        tabel_dokter.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataDokter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_dokter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_batal = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        TambahDokter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_batalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Id_Dokter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nama_dokter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Kontak = new javax.swing.JTextField();
        bt_Simpan = new javax.swing.JButton();
        bt_SimpanEdit = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tabel_dokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_dokter);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DATA DOKTER");

        bt_batal.setText("Batal");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_tambah.setText("Tambah Data");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataDokterLayout = new javax.swing.GroupLayout(dataDokter);
        dataDokter.setLayout(dataDokterLayout);
        dataDokterLayout.setHorizontalGroup(
            dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(dataDokterLayout.createSequentialGroup()
                .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataDokterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(dataDokterLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        dataDokterLayout.setVerticalGroup(
            dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );

        mainPanel.add(dataDokter, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DATA DOKTER");

        bt_batalTambah.setText("Batal");
        bt_batalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalTambahActionPerformed(evt);
            }
        });

        jLabel3.setText("ID DOKTER");

        Id_Dokter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Id_Dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_DokterActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Dokter");

        Nama_dokter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Kontak");

        Kontak.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Kontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KontakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id_Dokter)
                    .addComponent(Nama_dokter)
                    .addComponent(Kontak)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        bt_Simpan.setBackground(new java.awt.Color(0, 235, 21));
        bt_Simpan.setText("SIMPAN");
        bt_Simpan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        bt_SimpanEdit.setBackground(new java.awt.Color(0, 235, 21));
        bt_SimpanEdit.setText("SIMPAN EDIT");
        bt_SimpanEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bt_SimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahDokterLayout = new javax.swing.GroupLayout(TambahDokter);
        TambahDokter.setLayout(TambahDokterLayout);
        TambahDokterLayout.setHorizontalGroup(
            TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TambahDokterLayout.createSequentialGroup()
                        .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(TambahDokterLayout.createSequentialGroup()
                                .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_SimpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                        .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        TambahDokterLayout.setVerticalGroup(
            TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TambahDokterLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bt_SimpanEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(TambahDokter, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // batal utama
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        bt_edit.setVisible(false);
        
        bt_tambah.setVisible(true);
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:                                       
    int selectedRow = tabel_dokter.getSelectedRow();
    
    if (selectedRow != -1) {
        int idDokter = Integer.parseInt(tabel_dokter.getValueAt(selectedRow, 0).toString());

        int konfirmasi = JOptionPane.showConfirmDialog(null, 
            "Yakin ingin menghapus data ini?", "Konfirmasi", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection kon = koneksi.koneksiDb();
                String sql = "DELETE FROM dokter WHERE id_Dokter = ?";
                PreparedStatement pst = kon.prepareStatement(sql);
                pst.setInt(1, idDokter);
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tabel_dokter.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
    }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_batalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalTambahActionPerformed
        //  batal tambah data
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(dataDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
       
    }//GEN-LAST:event_bt_batalTambahActionPerformed

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO dokter VALUES (?, ?, ?)";
        Connection kon = koneksi.koneksiDb();
        PreparedStatement pst = kon.prepareStatement(sql);
        pst.setString(1, Id_Dokter.getText());
        pst.setString(2, Nama_dokter.getText());
        pst.setString(3, Kontak.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        Id_Dokter.setText("");
        Nama_dokter.setText("");
        Kontak.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
    }
    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(TambahDokter);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        bt_SimpanEdit.setVisible(false);
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void KontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KontakActionPerformed

    private void tabel_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dokterMouseClicked
        // TODO add your handling code here:
        bt_hapus.setVisible(true);
        bt_batal.setVisible(true);
        bt_edit.setVisible(true);
        
        bt_tambah.setVisible(false);
    }//GEN-LAST:event_tabel_dokterMouseClicked

    private void Id_DokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_DokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_DokterActionPerformed

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_dokter.getSelectedRow();
           
        if (selectedRow != -1) {
        // Ambil data dari tabel
        String id = tabel_dokter.getValueAt(selectedRow, 0).toString();
        String nama = tabel_dokter.getValueAt(selectedRow, 1).toString();
        String kontak = tabel_dokter.getValueAt(selectedRow, 2).toString();

        // Masukkan ke text field di panel Formulir
        Id_Dokter.setText(id);
        Nama_dokter.setText(nama);
        Kontak.setText(kontak);

        // Tampilkan panel formulir
        dataDokter.setVisible(false);
        TambahDokter.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin diedit!");
    }

    bt_Simpan.setVisible(false);
    bt_SimpanEdit.setVisible(true);
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_SimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanEditActionPerformed
        // TODO add your handling code here:
        try {
            int IdDokter = Integer.parseInt(Id_Dokter.getText());
            String nama = Nama_dokter.getText();
            String kontak = Kontak.getText();

            Connection kon = koneksi.koneksiDb();
            String sql = "UPDATE dokter SET Nama = ?, Kontak = ? WHERE id_Dokter = ?";
            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, kontak);
            pst.setInt(3, IdDokter);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
            Id_Dokter.setText("");
            Nama_dokter.setText("");
            Kontak.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_bt_SimpanEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_Dokter;
    private javax.swing.JTextField Kontak;
    private javax.swing.JTextField Nama_dokter;
    private javax.swing.JPanel TambahDokter;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_SimpanEdit;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalTambah;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JPanel dataDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tabel_dokter;
    // End of variables declaration//GEN-END:variables
}
