/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class Form_lp_keuangan extends javax.swing.JPanel {

    /**
     * Creates new form Form_lp_keuangan
     */
    public Form_lp_keuangan() {
        initComponents();
        tampildata();
        
    }
    
    private void tampildata() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Keuangan");
    model.addColumn("Nama layanan");
    model.addColumn("Total pendapatan");
    model.addColumn("Tanggal");

    try {
        Connection kon = koneksi.koneksiDb();

        String sql ="SELECT CONCAT('KEU-', LPAD(ROW_NUMBER() OVER (ORDER BY pembayaran.`tanggal_bayar`, layanan.`nama_layanan`), 5, '0')) AS `id_keuangan`," +
                    "     layanan.`nama_layanan` AS `nama_layanan`," +
                    "     SUM(pendaftaran_detail.`harga`) AS `total_pendapatan`," +
                    "     pembayaran.`tanggal_bayar` AS `tanggal`" +
                    "FROM" +
                    "     `pendaftaran` pendaftaran INNER JOIN `pendaftaran_detail` pendaftaran_detail ON pendaftaran.`id_pendaftaran` = pendaftaran_detail.`id_pendaftaran`" +
                    "     INNER JOIN `layanan` layanan ON pendaftaran_detail.`id_layanan` = layanan.`id_layanan`" +
                    "     INNER JOIN `pembayaran` pembayaran ON pendaftaran.`id_pendaftaran` = pembayaran.`id_pendaftaran`" +
                    "GROUP BY" +
                    "     pembayaran.`tanggal_bayar`," +
                    "     layanan.`nama_layanan`" +
                    "ORDER BY" +
                    "     pembayaran.`tanggal_bayar` ASC," +
                    "     layanan.`nama_layanan` ASC";

        PreparedStatement ps = kon.prepareStatement(sql);

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_keuangan"),
                rs.getString("nama_layanan"),
                rs.getInt("total_pendapatan"),
                rs.getDate("tanggal")
            });
        }

        tbl_laporan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_laporan = new javax.swing.JTable();
        dariTglTxt = new javax.swing.JLabel();
        dariTgl = new com.toedter.calendar.JDateChooser();
        sampaiTglTxt = new javax.swing.JLabel();
        sampaiTgl = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Laporan Keuangan");

        Cetak.setBackground(new java.awt.Color(102, 102, 255));
        Cetak.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Cetak.setText("CETAK");
        Cetak.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cetak.setBorderPainted(false);
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        tbl_laporan.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tbl_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_laporan);

        dariTglTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dariTglTxt.setText("Dari");

        dariTgl.setDateFormatString("yyyy-MM-dd");
        dariTgl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        sampaiTglTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sampaiTglTxt.setText("- Sampai");

        sampaiTgl.setDateFormatString("yyyy-MM-dd");
        sampaiTgl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dariTglTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dariTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sampaiTglTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sampaiTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dariTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sampaiTgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sampaiTglTxt)
                            .addComponent(dariTglTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Siapkan format tanggal (harus yyyy-MM-dd agar cocok dengan SQL)
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            // 2. Validasi: Pastikan tanggal tidak kosong
            if (dariTgl.getDate() == null || sampaiTgl.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Silakan pilih rentang tanggal terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Hentikan proses jika tanggal kosong
            }

            // 3. Ambil tanggal dan format ke string
            String tglMulai = sdf.format(dariTgl.getDate());
            String tglSelesai = sdf.format(sampaiTgl.getDate());

            // 4. Siapkan parameter untuk dikirim ke JasperReport
            // Nama parameter ("PARAM_TGL_MULAI") harus SAMA PERSIS dengan di .jrxml
            Map<String, Object> param = new HashMap<>();
            param.put("TGL_MULAI", tglMulai);
            param.put("TGL_SELESAI", tglSelesai);
            // Path ke file .jasper
            String reportPath = "src/report/keuangan.jasper";

            // Koneksi ke database
            Connection kon = koneksi.koneksiDb(); // pastikan kamu punya method koneksi seperti ini

            // Menjalankan laporan tanpa parameter
            JasperPrint jp = JasperFillManager.fillReport(reportPath, param, kon);

            // Menampilkan ke JasperViewer
            JasperViewer.viewReport(jp, false);

            // Jika ingin langsung print tanpa viewer
            // JasperPrintManager.printReport(jp, true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: \n" + e.getMessage());
    }
    }//GEN-LAST:event_CetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private com.toedter.calendar.JDateChooser dariTgl;
    private javax.swing.JLabel dariTglTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser sampaiTgl;
    private javax.swing.JLabel sampaiTglTxt;
    private javax.swing.JTable tbl_laporan;
    // End of variables declaration//GEN-END:variables
}
