/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.toedter.calendar.JDateChooser;
import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;
/**
 *
 * @author Basuki
 */
public class Form_lp_HasilPemeriksaan extends javax.swing.JPanel {
private DefaultTableModel tabmode;
    /**
     * Creates new form Form_lp_HasilPemeriksaan
     */
    public Form_lp_HasilPemeriksaan() {
        initComponents();
        tampildata();
    }

    private void tampildata() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nomor Pendaftaran");
        model.addColumn("Nama Pasien");
        model.addColumn("Tanggal Daftar");
        model.addColumn("Layanan");
        try {
        String sql = "SELECT p.id_pendaftaran, ps.nama AS nama_pasien, p.tanggal_daftar, l.nama_layanan " +
                     "FROM pendaftaran p " +
                     "JOIN pasien ps ON p.No_rm = ps.No_rm " +
                     "JOIN pendaftaran_detail pd ON p.id_pendaftaran = pd.id_pendaftaran " +
                     "JOIN layanan l ON pd.id_layanan = l.id_layanan " +
                     "WHERE p.status_hasil = 'sudah' " +
                     "ORDER BY p.id_pendaftaran ASC";

        Connection kon = koneksi.koneksiDb();
        Statement stm = kon.createStatement();
        ResultSet res = stm.executeQuery(sql);

        // Bersihkan tabel model dulu biar gak dobel
        model.setRowCount(0);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_pendaftaran"),
                res.getString("nama_pasien"),
                res.getString("tanggal_daftar"),
                res.getString("nama_layanan")
            });
        }

        tbl_laporan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cetak = new javax.swing.JButton();
        caridata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_cardat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_laporan = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Laporan Hasil Pemeriksaan");

        Cetak.setBackground(new java.awt.Color(102, 102, 255));
        Cetak.setText("CETAK");
        Cetak.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cetak.setBorderPainted(false);
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Cari Data");

        bt_cardat.setBackground(new java.awt.Color(255, 255, 255));
        bt_cardat.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_cardat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search (1) (1).png"))); // NOI18N
        bt_cardat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cardat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cardatActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_laporan.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tbl_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_laporan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 579, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caridata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cardat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
         //TODO add your handling code here:     try {
        try{
            //connection to data base
            Connection kon = koneksi.koneksiDb();
            //Parameter to jasper
            Map<String, Object> param = new HashMap<>();
            int selectedRow = tbl_laporan.getSelectedRow();
            Long  idpendaftaran = Long.parseLong(tbl_laporan.getValueAt(selectedRow, 0).toString());
            param.put("id_pendaftaran",idpendaftaran); // ambil dari input user atau combo box
            // pilih layanan
            String namalayanan = tbl_laporan.getValueAt(selectedRow, 3).toString();
            //String layanan = "hasil_"+namalayanan.toLowerCase().replace(" ","");
            param.put("layanan",namalayanan);
            //ambil logo
            InputStream logo = getClass().getResourceAsStream("/Img/logo_lab.png");
            param.put("logo", logo);
            
            //adress to file .jrxml
            JasperReport report = JasperCompileManager.compileReport("src/report/hasil.jrxml");
            
            //print report
            JasperPrint cetak = JasperFillManager.fillReport(report, param, kon);
            JasperViewer.viewReport(cetak, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_CetakActionPerformed

    private void bt_cardatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cardatActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nomor Pendaftaran");
        model.addColumn("Nama Pasien");
        model.addColumn("Tanggal Daftar");
        model.addColumn("Nama Layanan"); // ✅ Tambahkan kolom layanan

        String keyword = caridata.getText().trim();

        try {
            String sql = "SELECT p.id_pendaftaran, ps.nama AS nama_pasien, p.tanggal_daftar, l.nama_layanan " +
                         "FROM pendaftaran p " +
                         "JOIN pasien ps ON p.No_rm = ps.No_rm " +
                         "JOIN pendaftaran_detail pd ON p.id_pendaftaran = pd.id_pendaftaran " +
                         "JOIN layanan l ON pd.id_layanan = l.id_layanan " +
                         "WHERE (p.id_pendaftaran LIKE ? OR ps.nama LIKE ? OR l.nama_layanan LIKE ?) " + // ✅ Filter juga berdasarkan layanan
                         "AND p.status_hasil = 'sudah' " +
                         "ORDER BY p.id_pendaftaran ASC";
            Connection kon = koneksi.koneksiDb();
            PreparedStatement ps = kon.prepareStatement(sql);
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");

            ResultSet rs = ps.executeQuery();

            model.setRowCount(0); // Bersihkan tabel sebelum isi ulang

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pendaftaran"),
                    rs.getString("nama_pasien"),
                    rs.getString("tanggal_daftar"),
                    rs.getString("nama_layanan")
                });
            }

            tbl_laporan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_cardatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JButton bt_cardat;
    private javax.swing.JTextField caridata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_laporan;
    // End of variables declaration//GEN-END:variables
}
