/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import config.koneksi;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class form_pembayaran extends javax.swing.JPanel {

    /**
     * Creates new form form_pembayaran
     */
    public form_pembayaran() {
        initComponents();
        initComponents();
        loadNoPendaftaran();
        generateIdPembayaran();
        tglbayar.setText(LocalDate.now().toString());
        
        
        no_pendaftaran.addActionListener(e -> {
        String selectedId = (String) no_pendaftaran.getSelectedItem();
        if (selectedId != null) {
            isiDataDariPendaftaran(selectedId);
        }
    });
    }
    
    private void generateIdPembayaran() {
        try {
            Connection kon = koneksi.koneksiDb();
            LocalDate now = LocalDate.now();
            String tanggalStr = now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            String tanggalId = now.format(DateTimeFormatter.ofPattern("yyyyMMdd"));

            String sql = "SELECT COUNT(*) as total FROM pembayaran WHERE tanggal_bayar = ?";
            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, tanggalStr);
            ResultSet rs = pst.executeQuery();

            int urut = 1;
            if (rs.next()) {
                urut = rs.getInt("total") + 1;
            }
            String noUrutStr = String.format("%03d", urut);
            idPembayaran.setText("PB" + tanggalId + noUrutStr);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal generate ID: " + e.getMessage());
        }
    }
    private void loadNoPendaftaran() {
        try {
            Connection kon = koneksi.koneksiDb();
            String sql = "SELECT id_pendaftaran FROM pendaftaran WHERE status_bayar ='Belum'";
            PreparedStatement pst = kon.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                no_pendaftaran.addItem(rs.getString("id_pendaftaran"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load No Pendaftaran: " + e.getMessage());
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        no_pendaftaran = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rincian = new javax.swing.JTable();
        bt_simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        idPembayaran = new javax.swing.JFormattedTextField();
        biaya = new javax.swing.JFormattedTextField();
        tglbayar = new javax.swing.JFormattedTextField();
        nm_pasien = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nm_dokter = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(getPreferredSize());

        jLabel1.setBackground(new java.awt.Color(153, 0, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" PEMBAYARAN PEMERIKSAAN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setText("No Pembayaran:");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("No Pendaftaran");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal:");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Total Biaya :");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("Tabel Rincian");

        no_pendaftaran.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        no_pendaftaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nomer Pendaftaran" }));
        no_pendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_pendaftaranActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setText("Rp.");

        tbl_rincian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_rincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_rincian);

        bt_simpan.setBackground(new java.awt.Color(0, 255, 0));
        bt_simpan.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bt_simpan.setText("Simpan");
        bt_simpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_simpan.setBorderPainted(false);
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setText("Batal");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setBorderPainted(false);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setBorderPainted(false);

        idPembayaran.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        biaya.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        tglbayar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        nm_pasien.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("Nama Pasien : ");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel9.setText("Nama Dokter : ");

        nm_dokter.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(no_pendaftaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nm_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nm_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(260, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
         Connection kon = koneksi.koneksiDb();
        try {
            String sql = "INSERT INTO pembayaran (id_pembayaran, id_pendaftaran, tanggal_bayar, total_bayar) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, idPembayaran.getText());
            pst.setString(2, no_pendaftaran.getSelectedItem().toString());
            pst.setString(3, tglbayar.getText());
            pst.setString(4, biaya.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Pembayaran berhasil disimpan");
            
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan pembayaran: " + e.getMessage());
        }
        //UPDATE STATUS PEMBAYARAN
        
            try {
            String update = "UPDATE pendaftaran SET status_bayar = 'sudah' WHERE id_pendaftaran = ?";
            PreparedStatement pstUpdate = kon.prepareStatement(update);
            pstUpdate.setString(1, no_pendaftaran.getSelectedItem().toString());
            pstUpdate.executeUpdate();
            
            cetakNota();
            JOptionPane.showMessageDialog(this, "Status Sudah Diubah");
            resetForm();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Update Status" + e.getMessage());
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void no_pendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_pendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_pendaftaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField biaya;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JFormattedTextField idPembayaran;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField nm_dokter;
    private javax.swing.JFormattedTextField nm_pasien;
    private javax.swing.JComboBox<String> no_pendaftaran;
    private javax.swing.JTable tbl_rincian;
    private javax.swing.JFormattedTextField tglbayar;
    // End of variables declaration//GEN-END:variables

   private void isiDataDariPendaftaran(String idPendaftaran) {
        try {
            Connection kon = koneksi.koneksiDb();
            String sql = "SELECT p.nama AS nama_pasien, d.nama AS nama_dokter FROM pendaftaran pd JOIN pasien p ON p.No_rm = pd.No_rm JOIN dokter d ON d.id_Dokter = pd.id_Dokter WHERE pd.id_pendaftaran = ?";

            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, idPendaftaran);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nm_pasien.setText(rs.getString("nama_pasien"));
                nm_dokter.setText(rs.getString("nama_dokter"));
            }

            // Load detail layanan
            DefaultTableModel model = (DefaultTableModel) tbl_rincian.getModel();
            model.setRowCount(0);
            String detailSql = "SELECT l.nama_layanan, l.harga FROM pendaftaran_detail pd " +
                   "JOIN layanan l ON l.id_layanan = pd.id_layanan " +
                   "WHERE pd.id_pendaftaran = ?";
            PreparedStatement pstDetail = kon.prepareStatement(detailSql);
            pstDetail.setString(1, idPendaftaran);
            ResultSet rsDetail = pstDetail.executeQuery();
            int total = 0;
            while (rsDetail.next()) {
                String layanan = rsDetail.getString("nama_layanan");
                int harga = rsDetail.getInt("harga");
                model.addRow(new Object[]{layanan, harga});
                total += harga;
            }
            biaya.setText(String.valueOf(total));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data: " + e.getMessage());
        }
    }
   
   private void resetForm() {
    idPembayaran.setText("");
    no_pendaftaran.setSelectedIndex(0);
    tglbayar.setText(LocalDate.now().toString());
    nm_pasien.setText("");
    nm_dokter.setText("");
    biaya.setText("");
    
    DefaultTableModel model = (DefaultTableModel) tbl_rincian.getModel();
    model.setRowCount(0);

    generateIdPembayaran(); // Generate ulang ID baru
}
   
private void cetakNota(){
   try {
        // 1. Siapkan koneksi ke database
        Connection kon = koneksi.koneksiDb();
        
        Map<String, Object> param = new HashMap<>();
        param.put("id_pembayaran", idPembayaran.getText()); // Sesuaikan dengan nama parameter di report

        // 4. Load & compile file .jrxml
        JasperReport report = JasperCompileManager.compileReport("src/report/nota_pembayaran.jrxml");

        // 5. Isi report dengan data dari database
        JasperPrint print = JasperFillManager.fillReport(report, param, kon);

        // 6. Tampilkan report
        JasperViewer.viewReport(print, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
        e.printStackTrace();
    }

}
}
