/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Layanan extends javax.swing.JPanel {

    /**
     * Creates new form Form__Layanan
     */
    public Form_Layanan() {
        initComponents();
        tampilkanData();
        
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        bt_edit.setVisible(false);
    }
private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Layanan");
    model.addColumn("Nama Layanan");
    model.addColumn("Harga");

    try {
        String sql = "SELECT * FROM layanan";
        Connection kon = koneksi.koneksiDb();
        Statement stm = kon.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_layanan"),
                res.getString("nama_layanan"),
                res.getString("harga"),
            });
        }

        tabel_Layanan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        DataLayanan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_Layanan = new javax.swing.JTable();
        bt_batal = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        TambahLayanan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_Simpan = new javax.swing.JButton();
        bt_batalTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id_layanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_layanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        bt_SimpanEdit = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DATA LAYANAN");

        tabel_Layanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_Layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_LayananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_Layanan);

        bt_batal.setText("Batal");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_tambah.setText("Tambah Data");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataLayananLayout = new javax.swing.GroupLayout(DataLayanan);
        DataLayanan.setLayout(DataLayananLayout);
        DataLayananLayout.setHorizontalGroup(
            DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
            .addGroup(DataLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(DataLayananLayout.createSequentialGroup()
                        .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataLayananLayout.setVerticalGroup(
            DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(DataLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );

        mainPanel.add(DataLayanan, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tambah Layanan");

        bt_Simpan.setBackground(new java.awt.Color(0, 235, 21));
        bt_Simpan.setText("SIMPAN");
        bt_Simpan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        bt_batalTambah.setText("Batal");
        bt_batalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalTambahActionPerformed(evt);
            }
        });

        jLabel3.setText("ID DOKTER");

        id_layanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Nama Dokter");

        nama_layanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Kontak");

        harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_layanan)
                    .addComponent(nama_layanan)
                    .addComponent(harga)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 560, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        bt_SimpanEdit.setBackground(new java.awt.Color(0, 235, 21));
        bt_SimpanEdit.setText("SIMPAN EDIT");
        bt_SimpanEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bt_SimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahLayananLayout = new javax.swing.GroupLayout(TambahLayanan);
        TambahLayanan.setLayout(TambahLayananLayout);
        TambahLayananLayout.setHorizontalGroup(
            TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahLayananLayout.createSequentialGroup()
                .addGroup(TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TambahLayananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TambahLayananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 507, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(TambahLayananLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_SimpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TambahLayananLayout.setVerticalGroup(
            TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahLayananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(TambahLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_batalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_SimpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(TambahLayanan, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_batalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalTambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(DataLayanan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_batalTambahActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // batal utama
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        bt_edit.setVisible(false);

        bt_tambah.setVisible(true);
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(TambahLayanan);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_SimpanEdit.setVisible(false);
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_Layanan.getSelectedRow();

        if (selectedRow != -1) {
            int id_layanan = Integer.parseInt(tabel_Layanan.getValueAt(selectedRow, 0).toString());

            int konfirmasi = JOptionPane.showConfirmDialog(null,
                "Yakin ingin menghapus data ini?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    Connection kon = koneksi.koneksiDb();
                    String sql = "DELETE FROM layanan WHERE id_layanan = ?";
                    PreparedStatement pst = kon.prepareStatement(sql);
                    pst.setInt(1, id_layanan);
                    pst.executeUpdate();

                    DefaultTableModel model = (DefaultTableModel) tabel_Layanan.getModel();
                    model.removeRow(selectedRow);

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_Layanan.getSelectedRow();

        if (selectedRow != -1) {
            // Ambil data dari tabel
            String id = tabel_Layanan.getValueAt(selectedRow, 0).toString();
            String nama = tabel_Layanan.getValueAt(selectedRow, 1).toString();
            String kontak = tabel_Layanan.getValueAt(selectedRow, 2).toString();

            // Masukkan ke text field di panel Formulir
            id_layanan.setText(id);
            nama_layanan.setText(nama);
            harga.setText(kontak);

            // Tampilkan panel formulir
            DataLayanan.setVisible(false);
            TambahLayanan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diedit!");
        }

        bt_Simpan.setVisible(false);
        bt_SimpanEdit.setVisible(true);
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_SimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanEditActionPerformed
        // TODO add your handling code here:
        try {
            int Idlayanan = Integer.parseInt(id_layanan.getText());
            String nama = nama_layanan.getText();
            int Harga = Integer.parseInt(harga.getText());

            Connection kon = koneksi.koneksiDb();
            String sql = "UPDATE layanan SET nama_layanan = ?, harga = ? WHERE id_Dokter = ?";
            PreparedStatement pst = kon.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setInt(2, Harga);
            pst.setInt(3, Idlayanan);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
            id_layanan.setText("");
            nama_layanan.setText("");
            harga.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_bt_SimpanEditActionPerformed

    private void tabel_LayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_LayananMouseClicked
        // TODO add your handling code here:
        bt_hapus.setVisible(true);
        bt_batal.setVisible(true);
        bt_edit.setVisible(true);
        
        bt_tambah.setVisible(false);
    }//GEN-LAST:event_tabel_LayananMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataLayanan;
    private javax.swing.JPanel TambahLayanan;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_SimpanEdit;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalTambah;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_layanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nama_layanan;
    private javax.swing.JTable tabel_Layanan;
    // End of variables declaration//GEN-END:variables
}
