/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;

/**
 *
 * @author user
 */
public class Form_lp_Pendaftaran extends javax.swing.JPanel {

    /**
     * Creates new form Form_lp_Kinerja
     */
    public Form_lp_Pendaftaran() {
         setTitle("Laporan Pendaftaran");
        setSize(400, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);

        JLabel lblTitle = new JLabel("Laporan Pendaftaran");
        lblTitle.setBounds(100, 20, 200, 30);
        add(lblTitle);

        btnCetak = new JButton("CETAK");
        btnCetak.setBounds(140, 80, 100, 30);
        add(btnCetak);

        btnCetak.addActionListener(e -> cetakLaporan());
        
    }
    private void tampildata() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Dokter");
    model.addColumn("Nama Dokter");
    model.addColumn("Jumlah Pemeriksaan");
    model.addColumn("Tanggal Aktif");

    try {
        Connection kon = koneksi.koneksiDb();

//        // Format tanggal dari JDateChooser
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        String dari = sdf.format(Dari.getDate());
//        String sampai = sdf.format(Sampai.getDate());

        String sql = "SELECT d.id_dokter, d.Nama AS nama_dokter, d.aktif_mulai, " +
                 "COUNT(p.id_pendaftaran) AS jumlah_pemeriksaan " +
                 "FROM pendaftaran p " +
                 "JOIN dokter d ON p.id_dokter = d.id_dokter " +
                 "GROUP BY d.id_dokter, d.Nama, d.aktif_mulai " +
                 "ORDER BY jumlah_pemeriksaan DESC";

        PreparedStatement ps = kon.prepareStatement(sql);
//        ps.setString(1, dari);
//        ps.setString(2, sampai);

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_dokter"),
                rs.getString("nama_dokter"),
                rs.getInt("jumlah_pemeriksaan"),
                rs.getDate("aktif_mulai")
            });
        }

        tbl_laporan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }

    }

    private void cetakLaporan(String tglAwal, String tglAkhir) {
    try {
        Connection kon = koneksi.koneksiDb();
        String reportPath = "src/report/NGETES.jasper"; // Sesuaikan path file .jasper kamu

        // Parameter ke JasperReport
        Map<String, Object> params = new HashMap<>();
        params.put("startDate", java.sql.Date.valueOf(tglAwal));
        params.put("endDate", java.sql.Date.valueOf(tglAkhir));

        JasperPrint print = JasperFillManager.fillReport(reportPath, params, kon);
        JasperViewer.viewReport(print, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencetak laporan: " + e.getMessage());
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_laporan = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Laporan Pendaftaran");

        Cetak.setText("CETAK");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        tbl_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_laporan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        try {
            String url = "jdbc:mysql://localhost:3306/db_lab"; // Ganti sesuai nama database
            String user = "root";
            String pass = "";

            Connection conn = koneksi.koneksiDb(); // pastikan koneksi DB kamu di sini

            // Load file .jrxml
            String path = "src/report/pendaftaran.jrxml"; // Pastikan path benar
            JasperReport jr = JasperCompileManager.compileReport(path);
            // Path ke file .jrxml
            //        String reportPath = "src/report/NGETES.jrxml"; // atau .jrxml jika belum dikompilasi

            // Isi laporan tanpa parameter
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);

              // Tampilkan laporan
            JasperViewer viewer = new JasperViewer(jp, false);
            viewer.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mencetak laporan: " + ex.getMessage());
        }
    }//GEN-LAST:event_CetakActionPerformed

 public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new FormPendaftaran().setVisible(true);
        });
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_laporan;
    // End of variables declaration//GEN-END:variables
}
